version: 2
registries:
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: PAT
    password: ${{ secrets.BASE_CONTAINER_IMAGE_READER_DEPENDABOT }}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
    registries: [ghcr]
    labels: [dependencies, docker]