apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-attestations-opa-provider
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: artifact-attestations-opa-provider
  template:
    metadata:
      labels:
        run: artifact-attestations-opa-provider
    spec:
      serviceAccountName: opa-provider
      automountServiceAccountToken: true
      containers:
      - image: github/artifact-attestations-opa-provider:dev
        imagePullPolicy: IfNotPresent
        name: artifact-attestations-opa-provider
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        args:
        - -namespace=provider-system
        - -image-pull-secret=aa-ghcr-login-secret
        - -certs={{ .Values.certDir }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        {{- if .Values.clientCAFile }}
        volumeMounts:
        - name: gatekeeper-ca-cert
          mountPath: /tmp/gatekeeper
          readOnly: true
        {{- end }}
        volumeMounts:
        - name: provider-tls-cert
          mountPath: /certs
          readOnly: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: provider-tls-cert
        secret:
          secretName: provider-tls-cert
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
      {{- if .Values.clientCAFile }}
      volumes:
      - name: gatekeeper-ca-cert
        secret:
          secretName: gatekeeper-webhook-server-cert
          items:
          - key: ca.crt
            path: ca.crt
      {{- end }}
