{{- if and .Values.serverCert .Values.serverKey }}
apiVersion: v1
kind: Secret
metadata:
  name: provider-tls-cert
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.serverCert }}
  tls.key: {{ .Values.serverKey }}
{{- end }}
