apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-attestations-opa-provider
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: artifact-attestations-opa-provider
  template:
    metadata:
      labels:
        run: artifact-attestations-opa-provider
        {{- if .Values.azureClientId }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      automountServiceAccountToken: true
      containers:
      - image: ghcr.io/github/artifact-attestations-opa-provider:dev
        imagePullPolicy: IfNotPresent
        name: artifact-attestations-opa-provider
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
          seccompProfile:
            type: RuntimeDefault
        args:
        - -namespace={{ .Release.Namespace }}
        - -image-pull-secret={{ .Values.imagePullSecrets }}
        - -certs={{ .Values.certDir }}
        - -port={{ .Values.port }}
        - -trust-tomain={{ .values.trustDomain }}
        ports:
        - containerPort: {{ .Values.port }}
          protocol: TCP
        volumeMounts:
        - name: provider-tls-cert
          mountPath: {{ .Values.certDir }}
          readOnly: true
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: provider-tls-cert
        secret:
          secretName: provider-tls-cert
          items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
