kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opa-provider-role-binding
  namespace:  {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: opa-provider
  apiGroup: ""
roleRef:
  kind: Role
  name: opa-provider
  apiGroup: rbac.authorization.k8s.io
