apiVersion: v1
kind: Service
metadata:
  name: artifact-attestations-opa-provider
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    run: artifact-attestations-opa-provider
  sessionAffinity: None
