apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace:  {{ .Release.Namespace }}
  annotations:
    {{- if .Values.azureClientId }}
    azure.workload.identity/client-id: {{ .Values.azureClientId }}
    {{- end }}
