name: Integration tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: go.mod
      - name: Build
        run: |
          make build
      - name: Generate certificates
        run: |
          ./scripts/gen_certs.sh
      - name: Run tests
        run: |
          ./scripts/integration_test.sh
