name: Test rego examples

on:
  push:
    branches:
      - main
  pull_request: {}

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@b2b258e089860efaadaaf71bf6e3aecb4a3eeff1 # 2.4.0
        with:
          version: latest
      - name: Test
        run: |
          make test-rego
      - name: Verify constraint files
        shell: bash
        run: |
          ./scripts/diff_policy.sh
