name: Test rego examples

on:
  push:
    branches:
      - main
  pull_request: {}

permissions: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        persist-credentials: false
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # 2.2.0
        with:
          version: latest
      - name: Test
        run: |
          make test-rego
      - name: Verify constraint files
        shell: bash
        run: |
          ./scripts/diff_policy.sh
